version: '3'
services:
  node:
    image: node:10-alpine
    links:
      - redis
    user: node
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
    command: node dist/server.js
    ports:
      - "3000:3000"
  redis:
    image: redis
    ports:
      - "6379:6379"
